# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='New post', max_length=40, unique_for_date='publication_date'),
        ),
    ]
