# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170619_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.City'),
        ),
    ]
