# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170704_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='body',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploaded_image'),
        ),
    ]
