# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.CharField(blank=True, max_length=999992, null=True),
        ),
    ]
